# Generated by Django 2.2.16 on 2022-06-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, default=1, max_length=40, verbose_name='Проверочный код'),
            preserve_default=False,
        ),
    ]
